#Course Project: Reading & Analyzing Data

Rnames = read.csv("Resume Names.csv",header=T,na.strings="?")
names(Rnames)
summary(Rnames)

#Characters to numerics
Rnames$gender <- as.numeric(as.character(Rnames$gender))
is.numeric(Rnames$gender)
Rnames$ethnicity <- as.numeric(as.character(Rnames$ethnicity))
is.numeric(Rnames$ethnicity)
Rnames$quality <- as.numeric(as.character(Rnames$quality))
is.numeric(Rnames$quality)
Rnames$call <- as.numeric(as.character(Rnames$call))
is.numeric(Rnames$call)
Rnames$city <- as.numeric(as.character(Rnames$city))
is.numeric(Rnames$city)
Rnames$honors <- as.numeric(as.character(Rnames$honors))
is.numeric(Rnames$honors)
Rnames$military <- as.numeric(as.character(Rnames$military))
is.numeric(Rnames$military)
Rnames$holes <- as.numeric(as.character(Rnames$holes))
is.numeric(Rnames$holes)
Rnames$school <- as.numeric(as.character(Rnames$school))
is.numeric(Rnames$school)
Rnames$email <- as.numeric(as.character(Rnames$email))
is.numeric(Rnames$email)
Rnames$computer <- as.numeric(as.character(Rnames$computer))
is.numeric(Rnames$computer)
Rnames$special <- as.numeric(as.character(Rnames$special))
is.numeric(Rnames$special)
Rnames$college <- as.numeric(as.character(Rnames$college))
is.numeric(Rnames$college)
Rnames$equal <- as.numeric(as.character(Rnames$equal))
is.numeric(Rnames$equal)
Rnames$requirements <- as.numeric(as.character(Rnames$requirements))
is.numeric(Rnames$requirements)
Rnames$reqexp <- as.numeric(as.character(Rnames$reqexp))
is.numeric(reqexp)
Rnames$reqcomm <- as.numeric(as.character(Rnames$reqcomm))
is.numeric(Rnames$reqcomm)
Rnames$reqeduc <- as.numeric(as.character(Rnames$reqeduc))
is.numeric(Rnames$reqeduc)
Rnames$reqcomp <- as.numeric(as.character(Rnames$reqcomp))
is.numeric(Rnames$reqcomp)
Rname$reqorg <- as.numeric(as.character(Rnames$reqorg))
is.numeric(Rnames$reqorg)

summary(Rnames)
